// Production environment — AUTO-GENERATED by scripts/set-env.mjs, do not edit by hand.
// Values come from EARNIVO_API_BASE_URL / EARNIVO_API_KEY environment
// variables set in your deployment host's dashboard. This file is
// gitignored so real credentials never land in git history.
export const environment = {
  production: true,
  earnivo: {
    apiBaseUrl: "https://api.admobility.in/api",
    apiKey: "ak_6375bbe8747ecf38999bda63fa7c0bae6270c510ae9bddaa",
  },
} as const;
