// Production environment — AUTO-GENERATED by scripts/set-env.mjs, do not edit by hand.
// Values come from EARNIVO_API_BASE_URL / EARNIVO_API_KEY environment
// variables set in your deployment host's dashboard. This file is
// gitignored so real credentials never land in git history.
export const environment = {
  production: true,
  earnivo: {
    apiBaseUrl: "https://api.admobility.in/api",
    apiKey: "ak_9b504d51209aae38bc92fc7a1f1cda10bd9d9178c798ab93",
  },
} as const;
