#!/usr/bin/env node
// Regenerates src/environments/environment.prod.ts from environment
// variables before a production build, so real credentials never need to be
// committed to git. Configure these in your deployment host's dashboard
// (e.g. Vercel -> Project -> Settings -> Environment Variables):
//
//   EARNIVO_API_BASE_URL   The Earnivo API origin, including /api.
//   EARNIVO_API_KEY        Earnivo agent panel -> campaign -> Website
//                           Verification -> API Key.
//
// Both are optional. Leaving EARNIVO_API_KEY unset keeps the reward widget
// disabled, which is a safe default for any deployment not running an
// Earnivo campaign.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const outFile = path.join(scriptDir, '..', 'src', 'environments', 'environment.prod.ts');

const apiBaseUrl = process.env.EARNIVO_API_BASE_URL ?? '';
const apiKey = process.env.EARNIVO_API_KEY ?? '';

const contents = `// Production environment — AUTO-GENERATED by scripts/set-env.mjs, do not edit by hand.
// Values come from EARNIVO_API_BASE_URL / EARNIVO_API_KEY environment
// variables set in your deployment host's dashboard. This file is
// gitignored so real credentials never land in git history.
export const environment = {
  production: true,
  earnivo: {
    apiBaseUrl: ${JSON.stringify(apiBaseUrl)},
    apiKey: ${JSON.stringify(apiKey)},
  },
} as const;
`;

writeFileSync(outFile, contents, 'utf8');

console.log(
  apiKey
    ? '[set-env] environment.prod.ts written with an Earnivo API key from the environment.'
    : '[set-env] environment.prod.ts written without an Earnivo API key — the reward widget will be disabled. Set EARNIVO_API_KEY to enable it.',
);
